<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.31">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Daniel Redel">
<meta name="dcterms.date" content="2026-06-20">
<meta name="description" content="What if you could run a pricing survey without recruiting a single human — by having an LLM role-play hundreds of buyers? That’s the idea behind BeeSignal. But the first big run came back with a pseudo-R² of 0.911 and willingness-to-pay of $1,683 per seat, with every standard error exactly zero. This is the forensic trail from a too-good-to-be-true result down to its root cause — and what it taught me about simulating people.">

<title>When Synthetic Consumers Are Too Smart: A Perfect-Separation Post-Mortem – Daniel Redel</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../myprofile.jpg" rel="icon" type="image/jpeg">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-3ad3898019ac633b5dc008510ac09064.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-76702eb7cada84b330ed18131569fa4c.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css">

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Daniel Redel</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../myposts.html"> <i class="bi bi-pencil-square" role="img">
</i> 
<span class="menu-text">Blog</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../projects.html"> <i class="bi bi-folder" role="img">
</i> 
<span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../research.html"> <i class="bi bi-journal-text" role="img">
</i> 
<span class="menu-text">Research</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> <i class="bi bi-person" role="img">
</i> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/dannyredel"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/daniel-redel-14b052b6/"> <i class="bi bi-linkedin" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com/DannyRedel"> <i class="bi bi-twitter" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">When Synthetic Consumers Are Too Smart: A Perfect-Separation Post-Mortem</h1>
                  <div>
        <div class="description">
          What if you could run a pricing survey without recruiting a single human — by having an LLM role-play hundreds of buyers? That’s the idea behind BeeSignal. But the first big run came back with a pseudo-R² of 0.911 and willingness-to-pay of $1,683 per seat, with every standard error exactly zero. This is the forensic trail from a too-good-to-be-true result down to its root cause — and what it taught me about simulating people.
        </div>
      </div>
                          <div class="quarto-categories">
                <div class="quarto-category">Discrete Choice</div>
                <div class="quarto-category">Conjoint Analysis</div>
                <div class="quarto-category">LLM</div>
                <div class="quarto-category">Econometrics</div>
                <div class="quarto-category">Python</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Daniel Redel </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">June 20, 2026</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#first-what-is-a-synthetic-consumer-and-why-simulate-one" id="toc-first-what-is-a-synthetic-consumer-and-why-simulate-one" class="nav-link active" data-scroll-target="#first-what-is-a-synthetic-consumer-and-why-simulate-one">First: what is a “synthetic consumer,” and why simulate one?</a></li>
  <li><a href="#the-result-that-set-off-the-alarm" id="toc-the-result-that-set-off-the-alarm" class="nav-link" data-scroll-target="#the-result-that-set-off-the-alarm">The result that set off the alarm</a></li>
  <li><a href="#the-suspect-perfect-separation" id="toc-the-suspect-perfect-separation" class="nav-link" data-scroll-target="#the-suspect-perfect-separation">The suspect: perfect separation</a></li>
  <li><a href="#layer-1-what-did-the-llm-actually-do" id="toc-layer-1-what-did-the-llm-actually-do" class="nav-link" data-scroll-target="#layer-1-what-did-the-llm-actually-do">Layer 1 — what did the LLM actually do?</a></li>
  <li><a href="#layer-2-the-smoking-gun" id="toc-layer-2-the-smoking-gun" class="nav-link" data-scroll-target="#layer-2-the-smoking-gun">Layer 2 — the smoking gun</a></li>
  <li><a href="#layer-3-the-geometry-of-the-failure" id="toc-layer-3-the-geometry-of-the-failure" class="nav-link" data-scroll-target="#layer-3-the-geometry-of-the-failure">Layer 3 — the geometry of the failure</a></li>
  <li><a href="#the-fix" id="toc-the-fix" class="nav-link" data-scroll-target="#the-fix">The fix</a></li>
  <li><a href="#the-real-lesson" id="toc-the-real-lesson" class="nav-link" data-scroll-target="#the-real-lesson">The real lesson</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<blockquote class="blockquote">
<p>Part of <a href="https://beesignal.ai"><strong>BeeSignal</strong></a> — a pricing-research engine that runs experiments on LLM-generated synthetic consumers.</p>
</blockquote>
<p>A model that fits <em>too</em> well is not good news. It is a symptom. This is the story of a result so good it had to be wrong — and of what went wrong, which turned out to be a problem you can only have when your survey respondents are made of language instead of flesh.</p>
<p>But to see why it’s interesting, you first need to know what I was even trying to do.</p>
<section id="first-what-is-a-synthetic-consumer-and-why-simulate-one" class="level2">
<h2 class="anchored" data-anchor-id="first-what-is-a-synthetic-consumer-and-why-simulate-one">First: what is a “synthetic consumer,” and why simulate one?</h2>
<p>Companies spend a fortune answering one deceptively simple question: <em>what will people pay, and for which features?</em> The gold-standard method is <strong>conjoint analysis</strong> — a type of survey where, instead of asking “how much would you pay for feature X?” (people are terrible at answering that), you show respondents a series of product cards with different feature/price combinations and simply watch <strong>which ones they pick</strong>. From hundreds of those choices, a statistical model backs out how much each feature is secretly worth. It’s the same math behind how airlines price seats and how SaaS companies design their pricing tiers.</p>
<p>The catch: a real conjoint study means recruiting hundreds of qualified respondents, and it costs $50,000–$200,000 and takes months. So here’s the bet behind <a href="https://beesignal.ai">BeeSignal</a>: what if you replace the humans with an <strong>LLM role-playing each respondent</strong>? You give a language model a detailed persona — “you are a sales manager at a 50-person company, budget $500–2,000/month, you care about X and Y” — show it the same product cards, and record its choices. Do that a few hundred times and you have a synthetic survey for about <strong>$0.50</strong> instead of $50,000.</p>
<p>The whole pipeline looks like this:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="pipeline.png" class="img-fluid figure-img"></p>
<figcaption>How BeeSignal turns LLM personas into pricing estimates.</figcaption>
</figure>
</div>
<p>Two pieces deserve emphasis, because their combination is what’s genuinely new:</p>
<ul>
<li><strong>The estimation is real econometrics, not vibes.</strong> Step 4 is a <em>discrete-choice model</em> — specifically a <strong>multinomial logit (MNL)</strong>, the workhorse that earned McFadden a Nobel Prize. By randomizing which features appear on which card (a “D-optimal design”), the survey <em>experimentally identifies</em> the causal weight each attribute carries in a decision. It’s a randomized experiment, just run inside a survey.</li>
<li><strong>The respondents are synthetic.</strong> Bolting a frontier LLM onto the front of a classical discrete-choice pipeline — using simulated people as the experimental subjects — is a recent and still-unusual idea. It’s powerful precisely because it’s cheap enough to run dozens of times. But it also introduces failure modes that a textbook on conjoint analysis has never had to warn you about. This post is about one of them.</li>
</ul>
</section>
<section id="the-result-that-set-off-the-alarm" class="level2">
<h2 class="anchored" data-anchor-id="the-result-that-set-off-the-alarm">The result that set off the alarm</h2>
<p>I ran a conjoint study for a fictional B2B SaaS product (call it <em>Planwise</em>): 50 synthetic respondents, 16 choice tasks each, a clean MNL at the end. The estimation came back looking spectacular:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Signal</th>
<th>Value</th>
<th>What it should be</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Pseudo-R²</td>
<td><strong>0.911</strong></td>
<td>~0.2–0.4 for real conjoint</td>
</tr>
<tr class="even">
<td>Standard errors</td>
<td><strong>0.000 on all 13 coefficients</strong></td>
<td>strictly positive</td>
</tr>
<tr class="odd">
<td>Willingness-to-pay</td>
<td><strong>up to $1,683 / seat</strong></td>
<td>tens of dollars</td>
</tr>
</tbody>
</table>
<p>To anyone who has fit one of these models, this table is alarming, not impressive. A pseudo-R² of 0.911 on choice data is the statistical equivalent of a fire alarm. And standard errors of <em>exactly</em> zero are impossible in a healthy model — they mean the optimizer never actually found an answer. Something had silently broken, and the rest of this post is the autopsy.</p>
</section>
<section id="the-suspect-perfect-separation" class="level2">
<h2 class="anchored" data-anchor-id="the-suspect-perfect-separation">The suspect: perfect separation</h2>
<p>The hypothesis I started with was <strong>perfect separation</strong> — a classic pathology of logit models. Separation happens when the data is so clean that some combination of the features predicts every single choice <em>without error</em>. When that happens, the model’s log-likelihood keeps rising as the coefficients march off toward <span class="math inline">\pm\infty</span>; there’s no finite peak to climb to. The optimizer gives up at some large arbitrary value, and the curvature of the likelihood surface there — the Hessian — has flattened to nothing. Since the standard errors are computed by inverting that curvature,</p>
<p><span class="math display">
\widehat{\mathrm{SE}}(\hat\beta) = \sqrt{\operatorname{diag}\big(\,[-H(\hat\beta)]^{-1}\big)},
</span></p>
<p>a flattened (singular) Hessian yields standard errors that are numerically zero and coefficients that are meaningless.</p>
<p>The deeper question is <em>why a synthetic study would separate when a human one wouldn’t.</em> My bet: <strong>temperature</strong> — the LLM’s randomness dial. I had run it at <code>temperature=0.7</code>, low enough that each persona behaved almost deterministically, always picking the “obviously better” option and never wavering. Real humans are noisy, and that noise is exactly what keeps the math well-behaved. Strip it out and the data becomes too perfect to estimate from. Let’s prove it, in three layers.</p>
</section>
<section id="layer-1-what-did-the-llm-actually-do" class="level2">
<h2 class="anchored" data-anchor-id="layer-1-what-did-the-llm-actually-do">Layer 1 — what did the LLM actually do?</h2>
<p>Across 800 choices, the headline split looked unremarkable: 53.4% picked option A, 44.5% picked B, 2.1% chose neither. But two things stood out:</p>
<ul>
<li><strong>Confidence was pinned to the ceiling.</strong> Mean self-reported confidence was 0.90 (75th percentile: 0.95). The personas were almost never unsure.</li>
<li><strong>Counterbalancing agreement was 86.6%.</strong> Each task was shown twice with the options swapped, to catch position bias. Re-ask a <em>noisy</em> respondent a flipped question and they’ll disagree with themselves a fair fraction of the time. Agreeing with itself 86.6% of the time — at a temperature meant to inject randomness — is the first fingerprint of over-determinism.</li>
</ul>
<p>Suggestive, but not yet damning. For the smoking gun, I had to look at consistency.</p>
</section>
<section id="layer-2-the-smoking-gun" class="level2">
<h2 class="anchored" data-anchor-id="layer-2-the-smoking-gun">Layer 2 — the smoking gun</h2>
<p>Here’s the subtle part. A conditional logit conditions on each respondent individually — it explains the choices <em>within</em> a person. So separation is a <strong>within-respondent</strong> property. The right question isn’t “do all respondents agree with each other?” (they shouldn’t, and didn’t) but “is each individual respondent perfectly rationalizable by one fixed set of preferences?”</p>
<p>Two measurements answered it:</p>
<ul>
<li><strong>Price monotonicity: 100%.</strong> In all 650 tasks where one option was strictly cheaper, the cheaper one was chosen. Not 70%, not 85% — <em>every single time.</em></li>
<li><strong>Per-respondent consistency: 100%, for all 50 respondents.</strong> Each persona’s sixteen choices were perfectly explained by one deterministic ranking, with zero internal contradictions.</li>
</ul>
<p>That is precisely the data-generating process that breaks maximum likelihood: fifty individually-perfect, contradiction-free respondents. Pool fifty perfectly-separable panels and the likelihood has no finite peak. (Tellingly, the <em>pooled</em> per-attribute agreement was only ~55% — proof the personas had genuinely different tastes. They weren’t clones all picking the same thing; each was just internally, mechanically deterministic.)</p>
</section>
<section id="layer-3-the-geometry-of-the-failure" class="level2">
<h2 class="anchored" data-anchor-id="layer-3-the-geometry-of-the-failure">Layer 3 — the geometry of the failure</h2>
<p>The estimation layer confirmed it cold. The Hessian at the reported “optimum” was numerically singular:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Diagnostic</th>
<th>Value</th>
<th>Reading</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Condition number</td>
<td><strong>2.94 × 10²⁰</strong></td>
<td>≫ 10¹² → singular</td>
</tr>
<tr class="even">
<td>Rank deficiency</td>
<td><strong>8 of 13 eigenvalues ≈ 0</strong></td>
<td>likelihood is flat in 8 directions</td>
</tr>
<tr class="odd">
<td>Min eigenvalue</td>
<td>≈ 0 (not &gt; 0)</td>
<td>not a true maximum</td>
</tr>
</tbody>
</table>
<p>And the coefficients themselves gave the whole game away. A healthy conjoint has feature utilities in roughly the <span class="math inline">[-3, +3]</span> range. Here they had sprinted off the chart:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="coefficient_explosion.png" class="img-fluid figure-img"></p>
<figcaption>Every coefficient blew past the sane range — and reported a zero standard error.</figcaption>
</figure>
</div>
<p>Coefficients of <em>one hundred utils</em> aren’t estimates; they’re the optimizer running toward infinity until an iteration limit cut it off. The near-zero price coefficient (−0.06) is what then detonates the WTP numbers, since willingness-to-pay is <span class="math inline">-\beta_\text{attr}/\beta_\text{price}</span>: divide a 100-util feature effect by a price coefficient of −0.06 and you get the absurd $1,683.</p>
<p>The causal chain, end to end:</p>
<pre><code>temperature = 0.7
  → personas near-deterministic (always pick the "obviously better" option)
  → every respondent's choices are perfectly separable on their own
  → conditional log-likelihood has no finite maximum (β → ∞)
  → Hessian → singular at the cutoff point
  → standard errors = 0
  → β_price → 0, feature β → 100  ⟹  WTP explodes</code></pre>
</section>
<section id="the-fix" class="level2">
<h2 class="anchored" data-anchor-id="the-fix">The fix</h2>
<p>The diagnosis dictated the cure. The problem was never the model or the pipeline — it was that the respondents had no noise. So you add it back, in calibrated amounts:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Fix</th>
<th>Change</th>
<th>Why</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Raise temperature</strong></td>
<td><code>0.7 → 1.1</code></td>
<td>restores realistic ~75–85% consistency, breaking the separation</td>
</tr>
<tr class="even">
<td><strong>More respondents</strong></td>
<td><code>N = 50 → 100</code></td>
<td>satisfies the standard conjoint sample-size rule, shrinks SEs honestly</td>
</tr>
<tr class="odd">
<td><strong>L2 regularization</strong></td>
<td><code>λ = 0.1</code> on the MNL</td>
<td>a guaranteed backstop: a ridge penalty makes the Hessian invertible even if some separation survives</td>
</tr>
</tbody>
</table>
<p>Temperature is the lever that matters most; the ridge penalty is the seatbelt that bounds the coefficients and restores a finite, invertible Hessian no matter what.</p>
</section>
<section id="the-real-lesson" class="level2">
<h2 class="anchored" data-anchor-id="the-real-lesson">The real lesson</h2>
<p>The honest reason this case is worth writing up: the failure is <em>specific to synthetic data</em>, and it’s invisible if you only look at the summary stats. With human respondents you essentially never see perfect separation, because people are gloriously inconsistent. Swap in an LLM at low temperature and you manufacture respondents who are too rational to estimate from — and the model thanks you with a pseudo-R² of 0.911 that looks like a triumph instead of an alarm.</p>
<p>The lesson generalizes far beyond pricing: <strong>when you generate your own respondents, the noise is a modeling choice, not a nuisance to be minimized.</strong> A synthetic-data platform needs a diagnostic gate — separation checks, Hessian condition numbers, sane coefficient bounds — standing between “the run finished” and “the result is trustworthy.” A number that’s too good to be true usually is, and the most useful thing a model can do is tell you exactly <em>how</em> it broke.</p>


</section>

<a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Back to top</a></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>© 2026 Daniel Redel</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>